// First Rehabilitation — AI assistant backend (Vercel serverless function).
// The ANTHROPIC_API_KEY lives in a Vercel environment variable and never
// reaches the browser. kb.json is generated by build.py from the site's
// own content, so the assistant only knows what the site says.
import Anthropic from '@anthropic-ai/sdk';
import kb from './kb.json' with { type: 'json' };

const MODEL = 'claude-opus-4-8';

const SYSTEM = `You are the friendly virtual front-desk assistant on the website of First Rehabilitation of North Palm Beach, a family-owned outpatient rehabilitation clinic.

STRICT RULES — these override everything else:
- NEVER give medical advice, diagnose conditions, interpret symptoms, or promise treatment outcomes. For ANY clinical or symptom question, warmly redirect: that's a great question for our therapists, and the best next step is to book an evaluation — offer the phone number ${kb.clinic.phone} and the contact page (contact.html).
- Only answer questions about this clinic: its services, conditions treated, logistics, hours, location, insurance, team, podcast, and how to book. Politely decline anything off-topic (news, other businesses, general knowledge, coding, etc.) and steer back to how you can help with the clinic.
- If you don't know something, say so and point to the front desk at ${kb.clinic.phone} — NEVER guess hours, prices, availability, or policies beyond the facts below.
- Never ask for or encourage sharing of detailed medical history or sensitive health information in this chat.
- Keep a warm, professional tone befitting a family-owned Palm Beach clinic. Be concise: 1-3 short sentences or a short list. No emoji walls, at most one tasteful emoji occasionally.
- When booking comes up, mention they can tap "Request an appointment" right here in this chat, call ${kb.clinic.phone}, or use the contact page.

FACTS ABOUT THE CLINIC (your only source of truth):
${JSON.stringify(kb)}`;

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'method_not_allowed' });
    return;
  }
  if (!process.env.ANTHROPIC_API_KEY) {
    res.status(503).json({ error: 'not_configured' });
    return;
  }

  const body = req.body || {};
  const raw = Array.isArray(body.messages) ? body.messages : [];
  const messages = raw
    .filter((m) => m && (m.role === 'user' || m.role === 'assistant') && typeof m.content === 'string')
    .slice(-16)
    .map((m) => ({ role: m.role, content: m.content.slice(0, 2000) }));
  if (!messages.length || messages[messages.length - 1].role !== 'user') {
    res.status(400).json({ error: 'bad_request' });
    return;
  }

  const client = new Anthropic();
  try {
    const response = await client.messages.create({
      model: MODEL,
      max_tokens: 500,
      system: [{ type: 'text', text: SYSTEM, cache_control: { type: 'ephemeral' } }],
      messages,
    });
    if (response.stop_reason === 'refusal') {
      res.status(200).json({ reply: `I'm not able to help with that one — but I'd love to help with anything about our clinic! You can also reach our front desk at ${kb.clinic.phone}.` });
      return;
    }
    const reply = response.content
      .filter((b) => b.type === 'text')
      .map((b) => b.text)
      .join('')
      .trim();
    res.status(200).json({ reply: reply || `Hmm, I didn't catch that — could you rephrase? Or call our front desk at ${kb.clinic.phone}.` });
  } catch (err) {
    if (err instanceof Anthropic.RateLimitError) {
      res.status(429).json({ error: 'rate_limited' });
    } else {
      res.status(502).json({ error: 'upstream_error' });
    }
  }
}
